spring:
  application:
    name: demography-service

consul:
  host: ${CONSUL_HOST}
  port: ${CONSUL_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: ${SERVICE_HOST}
    ip-address: ${SERVICE_HOST}
    status-page-url: http://${SERVICE_HOST}:${server.port}/api/v1/health
    health-check-url: http://${SERVICE_HOST}:${server.port}/api/v1/health
    home-page-url: http://${SERVICE_HOST}:${server.port}/

http-client:
  connect-timeout: ${HTTP_CLIENT_CONNECT_TIMEOUT:5}
  response-timeout: ${HTTP_CLIENT_RESPONSE_TIMEOUT:10}
  max-total: ${HTTP_CLIENT_MAX_TOTAL:10}
  max-per-route: ${HTTP_CLIENT_MAX_PER_ROUTE:5}

service:
  host: ${SERVICE_HOST}

server:
  port: ${SERVICE_PORT}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

logging:
  level:
    ru.ifmo.soa: DEBUG
